import React from "react";
import {
  HomeOutlined,
  SecurityScanOutlined,
  SafetyCertificateOutlined,
  FormOutlined,
  CopyOutlined,
  BellOutlined,
  ReconciliationOutlined,
  FileSearchOutlined,
  FileProtectOutlined,
  FileTextOutlined,
  UsergroupAddOutlined,
} from "@ant-design/icons";

import { FindDocument, registration, user_group } from "../pages";

const HomeRoutes = {
  sub_menu: [
    {
      Id: 1,
      icon: <HomeOutlined />,
      path: "/home/search_document_warehouse",
      component: "",
      wording: "ค้นหากล่องเอกสาร <br/> (สำหรับเจ้าหน้าที่งานคลัง)",
      menu_wording: "ค้นหากล่องเอกสาร",
      menu_id: "MWH1001",
    },
    {
      Id: 2,
      icon: <SecurityScanOutlined />,
      path: "/home/search_document_user",
      component: FindDocument,
      wording: "ค้นหาเอกสาร <br/> (สำหรับผู้ขอเบิกเอกสาร)",
      menu_wording: "ค้นหาเอกสาร / ขอเบิกเอกสาร",
      menu_id: "MWH1002",
    },
    {
      Id: 3,
      icon: <SafetyCertificateOutlined />,
      path: "/home/store_document",
      component: "StoreDocument",
      wording: "จัดเก็บเอกสาร",
      menu_wording: "จัดเก็บเอกสาร",
      menu_id: "MWH1003",
    },
    {
      Id: 4,
      icon: <FormOutlined />,
      path: "/home/requisition_document",
      component: "Requisition",
      wording: "เบิกเอกสาร",
      menu_wording: "เบิก / คืนเอกสาร",
      menu_id: "MWH1004",
    },
    {
      Id: 5,
      icon: <CopyOutlined />,
      path: "/home/transpose_document",
      component: "MoveDocument",
      wording: "ย้ายเอกสาร",
      menu_wording: "โอนย้ายเอกสาร",
      menu_id: "MWH1005",
    },
    {
      Id: 6,
      icon: <BellOutlined />,
      path: "/home/tracking_document",
      component: "TrackDocument",
      wording: "ติดตามการเบิกเอกสาร",
      menu_wording: "ติดตามการเบิกเอกสาร",
      menu_id: "MWH1006",
    },
    {
      Id: 7,
      icon: <ReconciliationOutlined />,
      path: "/home/registration_document",
      component: registration,
      wording: "ทะเบียนตรวจรับเอกสาร",
      menu_wording: "ทะเบียนตรวจรับเอกสาร",
      menu_id: "MWH1007",
    },
    {
      Id: 8,
      icon: <FileSearchOutlined />,
      path: "/home/requisition_list_report",
      component: "RequistReport",
      wording: "รายการใบเบิกเอกสาร",
      menu_wording: "รายการใบเบิกเอกสาร",
      menu_id: "MWH2001",
    },
    {
      Id: 9,
      icon: <FileProtectOutlined />,
      path: "/home/requisition_conclusion_report",
      component: "RequisconclusionReport",
      wording: "สรุปผลการปฏิบัติงานการเบิกเอกสาร",
      menu_wording: "สรุปผลการปฏิบัติงานการเบิกเอกสาร",
      menu_id: "MWH2002",
    },
    {
      Id: 10,
      icon: <FileTextOutlined />,
      path: "/home/claim_statistics_report",
      component: "ClaimStatisticsReport",
      wording: "รายงานสถิติการจัดเก็บเอกสารสินไหม",
      menu_wording: "รายงานสถิติการจัดเก็บเอกสารสินไหม",
      menu_id: "MWH2003",
    },
    {
      Id: 11,
      icon: <UsergroupAddOutlined />,
      path: "/home/maintain/group",
      component: user_group,
      wording: "กลุ่มผู้ใช้งาน",
      menu_wording: "กลุ่มผู้ใช้งาน",
      menu_id: "MWH3001",
    },
    // {
    //   Id: 12,
    //   path: "/home/maintain/user",
    //   component: "Resgistration",
    //   wording: "หน้าจอผู้ใช้งาน",
    //   menu_wording: "หน้าจอผู้ใช้งาน",
    //   menu_id: "MWH3002",
    // },
  ],
};

export default HomeRoutes;
