export default {
  home_page_wording: "ระบบคลังเอกสารสินไหม",
  login_footer: "Copyright © 2564, Thai Life Insurance Public Co. Ltd",
  login_success: "เข้าสู่ระบบสำเสร็จ",
  logout_success: "ออกจากระบบสำเร็จ",
  login_failed: "ไม่สามารถเข้าสู่ระบบได้",
  login_failed_description: "เกิดปัญหาการเชื่อมต่อระบบส่วนกลาง กรุณารอสักครู่",
  login_warning: "แจ้งเตือน ! ",
  login_warning_description: "กรุณาตรวจสอบความถูกต้องของข้อมูลอีกครั้ง",
  login_page_title: "ลงชื่อเข้าใช้งานระบบ",
  form_notice_message: "กรุณากรอกข้อมูล!",
  username_placeholder: "รหัสพนักงาน",
  passWord_placeholder: "รหัสผ่าน",
  claim_warehouse_title: "คลังเอกสารสินไหม",
  profile_wording: "โปรไฟล์",
  logout_wording: "ออกจากระบบ",
  search_button: "Search",
  claim_box_no: "เลขที่กล่องสินไหม",
  claim_no: "เลขที่เรื่องสินไหม",
  claim_warehouse_no: "เลขที่กล่องคลัง",
  claim_doc_type: "ประเภทเอกสาร",
  action_username: "ผู้จัดเก็บ",
  action_date: "วันที่จัดเก็บ",
  claim_status: "สถานะ",
};
